### ISSUE TITLE
Requirements.txt..?

### ISSUE THREAD

**Issue by SamTheWarlock** [ncdulo/suppylement#8]
Are you planning to somewhat push this to heroku? Not sure why you'd need _requirements.txt_.

**Comment by ncdulo** [comment]
I haven't intended for this project to be pushed to Heroku. Actually wasn't even totally sure what that is until I read this issue. The intention behind added `requirements.txt` was so that a user can have a list of dependencies and versions. For my own use, I create a Python Virtual Environment and then can use `pip` to install anything listed in `requirements.txt`. The benefit to this is a user does not need to install the dependencies system-wide or user-wide, where they may potentially conflict with others.

I may be wrong, but I think `requirements.txt` is also used by PyPi, which I may consider adding the project to in the future.

For example, in the current state of the project after cloning this repository, a user could run:
```
python3.6 -m venv .env
source .env/bin/activate
pip install -r requirements.txt
```
To create a virtual environment specific to this directory, activate it, then install all required packages into this directory. Everything self-contained without effecting the rest of the system. I suppose the `requirements.txt` *could* be used for Heroku or similar. It's original intent was for installing dependencies via `pip`.

**Comment by ncdulo** [comment]
No further responses back and no real discussion at this time. Closed.
